### ISSUE TITLE
The View attribute value is not generated in the catalogue

### ISSUE THREAD

**Issue by Renaud-Marteleur** [ThalesGroup/xsmp-modeler-core#143]
Since upgrading XSMP to v1.1.0, regenerating a package lead to the following changes:

![image](https://github.com/ThalesGroup/xsmp-modeler-core/assets/127129501/dd802385-19c0-4516-9f21-8c301a3dac89)

The xsmpcat source is the following:
![image](https://github.com/ThalesGroup/xsmp-modeler-core/assets/127129501/4a834b1c-da5e-4c10-882e-adf08e961270)

The selected profile is ESA CDK.
Eclipse used:

> Eclipse DSL Tools (includes Incubating components)
> 
> Version: 2024-03 (4.31.0)
> Build id: 20240307-1437

Note: the code is generated correctly, with the expected View value.

**Comment by ydaveluy** [comment]
I confirm the issue, it affects also the content assist that does not provide proposals for enumeration values

**Comment by ydaveluy** [comment]
The issue should be fixed with https://github.com/ThalesGroup/xsmp-modeler-core/releases/tag/v1.1.1
