### ISSUE TITLE
.smpcat file is not re-generated after modifications and ctrl-s

### ISSUE THREAD

**Issue by ghazitlili** [ThalesGroup/xsmp-modeler-core#146]
Since upgrading XSMP to v1.1.1, after modifications of the .xsmpcat the .smpcat  is not updated 

Eclipse DSL Tools (includes Incubating components)

Version: 2024-03 (4.31.0)
Build id: 20240307-1437

Note: the code is generated correctly.

**Comment by ydaveluy** [comment]
Do you have the SMP tool enabled in your xsmp.project file ?
```
tool "org.eclipse.xsmp.tool.smp"
```

**Comment by ghazitlili** [comment]
> Do you have the SMP tool enabled in your xsmp.project file ?
> 
> ```
> tool "org.eclipse.xsmp.tool.smp"
> ```

No it is not enabled.

**Comment by ydaveluy** [comment]
In previous RC it was implicitly enabled and defined in Eclipse configuration. With the official release you need to explicitly define what is used.

Can you confirm that if you add the SMP tool in your xsmp.project, smpcat files are generated ?

You can find some additional documentation in https://xsmp-modeler.readthedocs.io/en/latest/user-guide.html#project-configuration

**Comment by ghazitlili** [comment]
> In previous RC it was implicitly enabled and defined in Eclipse configuration. With the official release you need to explicitly define what is used.
> 
> Can you confirm that if you add the SMP tool in your xsmp.project, smpcat files are generated ?
> 
> You can find some additional documentation in https://xsmp-modeler.readthedocs.io/en/latest/user-guide.html#project-configuration

Yes indeed it works. Thank you
