### ISSUE TITLE
CLI generation does not seem to produce files

### ISSUE THREAD

**Issue by aingenito-telespazio** [ThalesGroup/xsmp-modeler-core#15]
Hello. I've tried to generate a catalogue starting from the xsmpcat.

I've built the CLI from the tag `v1.1.0-rc1`, and used it as:

```
java -jar org.eclipse.xsmp.cli.jar -g
```

And I got a good output:

```
0    INFO  - Loading ECSS SMP library ...
354  INFO  - Done.
357  INFO  - Loading ..../Test.xsmpcat ...
426  INFO  - Done.
427  INFO  - Generating ..../Test.xsmpcat ...
427  INFO  - Done.
428  INFO  - Executed in 0.43 s
```

but I could not see any file generated.

I tried both in a project and with just a xsmpcat file.

In the IDE generation works without issues.

Could you help me figure out what I'm doing wrong?

**Comment by ydaveluy** [comment]
The [wiki](https://github.com/ThalesGroup/xsmp-modeler-core/wiki/User-guide#command-line-interface) is updated.

**Comment by aingenito-telespazio** [comment]
No file generated :-(.

I'm attaching the test project, in case it could help.
[TestProject.tar.gz](https://github.com/ThalesGroup/xsmp-modeler-core/files/11099641/TestProject.tar.gz)

**Comment by aingenito-telespazio** [comment]
Not sure if this could help, but `outputConfigurationProvider.getOutputConfigurations()` is empty.

**Comment by ydaveluy** [comment]
I just check the code and https://github.com/ThalesGroup/xsmp-modeler-core/tree/main/org.eclipse.xsmp.cli is an empty CLI with just validation.

The generation plugin for smpcat/smppkg file is missing. Let me an hour and I fix this :-)

**Comment by ydaveluy** [comment]
Can you test the branch 15-cli-generation-does-not-seem-to-produce-files ?

The CLI for smpcat/smppkg tool is in org.eclipse.xsmp.tool.smp.cli project:
```
cd ~/eclipse-workspace/TestProject
java -jar /path/to/org.eclipse.xsmp.tool.smp.cli.jar
```

**Comment by aingenito-telespazio** [comment]
Sorry, no change.
I'll try to debug in Eclipse.

**Comment by ydaveluy** [comment]
Which files do you expect to generate and which CLI are you running ?

There is one CLI per profile and tool. In your attached TestProject you are using the Xsmp SDK Profile and the SMP model generator. 

To generate the files from the command line, you have to run the following CLI:
-  [org.eclipse.xsmp.tool.smp.cli](https://github.com/ThalesGroup/xsmp-modeler-core/tree/15-cli-generation-does-not-seem-to-produce-files/org.eclipse.xsmp.tool.smp.cli) should generate the smpcat/smppkg in the smdl-gen folder.
-  [org.eclipse.xsmp.profile.xsmp_sdk.cli](https://github.com/ThalesGroup/xsmp-modeler-core/tree/15-cli-generation-does-not-seem-to-produce-files/org.eclipse.xsmp.profile.xsmp_sdk.cli) should generate c++ source files for the XSMP-SDK profile


The [org.eclipse.xsmp.cli](https://github.com/ThalesGroup/xsmp-modeler-core/tree/15-cli-generation-does-not-seem-to-produce-files/org.eclipse.xsmp.cli) does not generate anything: it is the base plugin for all others CLI.

**Comment by aingenito-telespazio** [comment]
I see!
Ok sorry, stupid me. I can confirm that it works :-).
