### ISSUE TITLE
Overloaded operations

### ISSUE THREAD

**Issue by Renaud-Marteleur** [ThalesGroup/xsmp-modeler-core#161]
It is clear that two operations destined to be published shall not have the same name. Here I have a design where an interface defines an operation (let's say: `Foo(int)`) and a model implementing that interface defines a user operation (destined to be published/invokable) with the same name but different signature (let's say `Foo(string)`).

Design:
```
IFooer
  + ::Smp::String8 Foo(::Smp::Int32) = 0

Fooer : IFooer
  + ::Smp::String8 Foo(::Smp::Int32)
  + ::Smp::String8 Foo(::Smp::String8) // --> shall be invokable
```

Currently, that design leads to a code (with ESA CDK) looking like this:
```
Help::template AddIfMissing<::Smp::String8, ::Smp::String8>(
    handlers,
    "Foo",
    ::Smp::PrimitiveTypeKind::PTK_String8,
    &Fooer::Foo);
```
This code does not compile because `&Fooer::Foo` has an unresolved type.

A way to explicit the targeted method (and make that code compile) would be to add a static cast like so:
```
Help::template AddIfMissing<::Smp::String8, ::Smp::String8>(
    handlers,
    "Foo",
    ::Smp::PrimitiveTypeKind::PTK_String8,
    static_cast<::Smp::String8 (FooerGen::*) (::Smp::String8)>(&Fooer::Foo));
```
We can see that the type in the static cast expression can be deduced from the type already provided to `AddIfMissing`. From the generator point of view, this is not ambiguous.

Would it be possible to generate the code like this?

**Comment by ydaveluy** [comment]
Hello, yes it is possible to update the generator.

Is it possible to change from 
```c++
Help::template AddIfMissing<::Smp::String8, ::Smp::String8>(
    handlers,
    "Foo",
    ::Smp::PrimitiveTypeKind::PTK_String8,
    static_cast<::Smp::String8 (FooerGen::*) (::Smp::String8)>(&Fooer::Foo));
```
to 
```c++
Help::template AddIfMissing<::Smp::String8, ::Smp::String8>(
    handlers,
    "Foo",
    ::Smp::PrimitiveTypeKind::PTK_String8,
    static_cast<::Smp::String8 (Fooer::*) (::Smp::String8)>(&Fooer::Foo));
```
(I removed the Gen from FooerGen) ?

**Comment by Renaud-Marteleur** [comment]
I confirm that:
* with the provided repository, the code is generated with the mentioned `static_cast`, and it compiles
* if I add a `const` qualifier to the return parameter, or any other parameter, the generated code does not compile
* if I then manually add the `const` qualifiers in the `static_cast` type, it compiles

(Thanks for this quick reaction !)

**Comment by ydaveluy** [comment]
Thanks for the feedback :-)

Here is the [repository](https://github.com/user-attachments/files/17200880/org.eclipse.xsmp.repository.zip) with the fix for const attribute. 

To be sure can you check that this operation compile properly ?
```
@Const
def @Const String8 Foo(@Const String8 param)
```

**Comment by Renaud-Marteleur** [comment]
Confirmed: it's all good now ;-)

**Comment by ydaveluy** [comment]
I will release soon the version 1.1.4. It will probably be the latest version before moving to https://github.com/ydaveluy/xsmp-modeler
