### ISSUE TITLE
AsciiDoc generator tool extension

### ISSUE THREAD

**Issue by ydaveluy** [ThalesGroup/xsmp-modeler-core#55]
Add a tool to generate AsciiDoc from a catalogue.

The AsciiDoc format is described in https://docs.asciidoctor.org/asciidoc/latest/

The extension shall generate an adoc file that is a mirror of the catalogue in adoc format. This generated adoc can be then customized with a provided template adoc file.

**Comment by cyrilvrousos-tas** [comment]
Here is a first preview of a document generated by the Adoc tool, based on BSLNG catalogue. Feedback is welcome!
[adoc-tool-document.pdf](https://github.com/ThalesGroup/xsmp-modeler-core/files/14792004/adoc-tool-document.pdf)

**Comment by jvallade** [comment]
Hi @cyrilvrousos-tas 
I had a quick look at the generated doc, and it looks promising :) 
I just had a small issue : I sometime get an error message saying the current page contains an error : 
![image](https://github.com/ThalesGroup/xsmp-modeler-core/assets/20614081/6ba1f968-460a-42ee-a048-b7430f6bbec5)

It does not always appear on the same page, so I'm not sure what's causing the issue. I'm using Acrobat Reader to read the document.

**Comment by ydaveluy** [comment]
Hi @jvallade 
I tested with a lot of pdf readers including web browsers, Acrobat reader DC version 2019.012.20034 and cannot reproduce the issue.

But with an online pdf validator( https://avepdf.com/pdfa-validation) some errors were detected. We will investigate.

**Comment by jvallade** [comment]
For info, I used Acrobat version 2022.001.20117

**Comment by cyrilvrousos-tas** [comment]
Here is a new version of the auto-generated document : [adoc-tool-document.pdf](https://github.com/ThalesGroup/xsmp-modeler-core/files/14919710/adoc-tool-document.pdf)
Adoc file :  [bslng_smp_full-gen.adoc.txt](https://github.com/ThalesGroup/xsmp-modeler-core/files/14919786/bslng_smp_full-gen.adoc.txt)
Xsmpcat file : [bslng.xsmpcat.txt](https://github.com/ThalesGroup/xsmp-modeler-core/files/14919796/bslng.xsmpcat.txt)

@jvallade I removed the logo, can you tell me if this has fixed the issue you encountered?

**Comment by jvallade** [comment]
Hi @cyrilvrousos-tas 
I just tested the new version of the document, and I did not get any error. 
Thanks
